[package]
name = "string2path"
version = "0.1.0"
authors = ["Hiroaki Yutani <yutani.ini@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.0"
lyon = "0.16.0"
rusttype = "0.9.2"
