# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib string2path, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}


string2path_family <- function(text, font_family, font_weight, font_style, tolerance) {
  .Call(savvy_string2path_family__impl, text, font_family, font_weight, font_style, tolerance)
}


string2path_file <- function(text, font_file, tolerance) {
  .Call(savvy_string2path_file__impl, text, font_file, tolerance)
}


string2stroke_family <- function(text, font_family, font_weight, font_style, tolerance, line_width) {
  .Call(savvy_string2stroke_family__impl, text, font_family, font_weight, font_style, tolerance, line_width)
}


string2stroke_file <- function(text, font_file, tolerance, line_width) {
  .Call(savvy_string2stroke_file__impl, text, font_file, tolerance, line_width)
}


string2fill_family <- function(text, font_family, font_weight, font_style, tolerance) {
  .Call(savvy_string2fill_family__impl, text, font_family, font_weight, font_style, tolerance)
}


string2fill_file <- function(text, font_file, tolerance) {
  .Call(savvy_string2fill_file__impl, text, font_file, tolerance)
}


dump_fontdb_impl <- function() {
  .Call(savvy_dump_fontdb_impl__impl)
}


