# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_string2path_wrappers", use_symbols = TRUE, package_name = "string2path")

#' @docType package
#' @usage NULL
#' @useDynLib string2path, .registration = TRUE
NULL

string2path_impl <- function(text, font_family, font_weight, font_style, tolerance) .Call(wrap__string2path_impl, text, font_family, font_weight, font_style, tolerance)

string2stroke_impl <- function(text, font_family, font_weight, font_style, tolerance, line_width) .Call(wrap__string2stroke_impl, text, font_family, font_weight, font_style, tolerance, line_width)

string2fill_impl <- function(text, font_family, font_weight, font_style, tolerance) .Call(wrap__string2fill_impl, text, font_family, font_weight, font_style, tolerance)

dump_fontdb_impl <- function() .Call(wrap__dump_fontdb_impl)

