on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: R-CMD-check (without Rust)

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release', rtools-version: '42'}
          - {os: windows-latest, r: 'devel',   rtools-version: '42'}
          - {os: macOS-latest,   r: 'release'}
          # TODO: test M1 macOS

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      # Ensure there's no cargo installed
      - name: Uninstall cargo
        run: |
          rm $(rustup which cargo)

      - uses: r-lib/actions/setup-r@v2
        id: install-r
        with:
          r-version: ${{ matrix.config.r }}
          rtools-version: ${{ matrix.config.rtools-version }}
          # TODO: Enable RSPM where possible
          use-public-rspm: false
          # use-public-rspm: ${{ matrix.config.r != 'devel' }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
